name: Build and Publish to v3
on: workflow_dispatch
jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Docker hub login
        run: docker login -p ${{ secrets.DOCKER_PASS }} -u ${{ secrets.DOCKER_USER }}
      - name: Build Container
        run: docker build -t sonarr:latest .
      - name: Tag container
        run: docker tag sonarr:latest "${{ secrets.DOCKER_USER }}/sonarr:latest"
      - name: Push container
        run: docker push "${{ secrets.DOCKER_USER }}/sonarr:latest"
      - name: Docker logout
        run: docker logout
